spring:
  application:
    name: authSpringSecurity

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    livereload:
      enabled: true
